### ISSUE TITLE
Wishlist: Adjust fire breath animation of EE Dragon

### ISSUE THREAD

**Issue by sevu** [ProditorMagnus/Ageless-for-1-14#11]
There are multiple fire breath macros in mainline, and it is possible to set an offset to have the starting coordinates of the animation match the mouth in the sprite.

**Comment by sevu** [comment]
Hmmm, the Fire Dragons coordinates are pretty close

**Comment by ProditorMagnus** [comment]
Needs more work learning about animations than I currently want to do.

**Comment by sevu** [comment]
I tried it, and I didn't figure out how to read the offset coordinates.

**Comment by sevu** [comment]
halo_y and halo_y are offset from the center of an image.
> the position the halo is displayed in pixel relative to the unit's center. These are directional, taking into account the direction the unit is facing (wiki)

The last sentence is not true. The direction does not matter – it's always x form centre to the right, or y from the centre to the bottom.

The other confusing part is that the fire breath images oversized, and the projectile is thus staring from the side, not the middle, if no offset is specified. One needs an Y-offset of 40-50 for the north/south images to get started. For the Diagonal ones it's 20-30 X and Y offset (both, because diagonal).

Implemented in 39b1051
