### ISSUE TITLE
Wrong image paths / missing images in 4.23

### ISSUE THREAD

**Issue by stevecotton** [ProditorMagnus/Ageless-for-1-14#13]
This should probably be fiend_attack.png, and there's two references to it in this .cfg:
`BEEM_units/anakes/Fiend.cfg:                image="units/anakes/fiend_attack1.png"`

Probably raindancer-defend-melee.png, but there's no -ranged.png equivalent.
`imperial_units/elves-wild/Raindancer.cfg:                image="units/elves-wild/raindancer-defend.png"`

This looks like a missing image, as fauno_a2die[1,2,4,5,6].png all exist.
`BEEM_units/wood_warriors/Faun_Sharpshooter.cfg:            image="units/wood_warriors/fauno/fauno_a2die3.png"`

Could be either skeletal-mage-knight.png or skeletal-mage-rider.png. Probably the knight, because the following lines in the .cfg include type=AE_ele_Skeletal_Spear_Fighter,
`factions/RPG/RPG-ELE.cfg:    image="units/undead-skeletal-horned/skeletal-mage.png"`

**Comment by ProditorMagnus** [comment]
re #4

**Comment by ProditorMagnus** [comment]
Will need to add check collecting all referenced relative image paths and comparing it to directory list of loaded binary paths.

**Comment by stevecotton** [comment]
Noticed this in 4.24, but the .cfg files are the same as 4.23, except for the removal of the poison sound.

The EOS's AE_stf_triththa_Giant_Squid, shows "image not found" when defending.
```
    {DEFENSE_ANIM "units/dwarves/young-cuttlefish-defend-2.png" "units/dwarves/young-cuttlefish-defend-1.png" squishy-hit.wav }
    [death]
        [frame]
            image="units/dwarves/young-cuttlefish-die-[1~6].png:100"
        [/frame]
    [/death]
```
There's only `-defend.png`, `-die-1.png` and `-die-2.png`. The `units/dwarves/young-cuttlefish-` part seems correct, although I'd suggest renaming them to "giant-squid-", the "young-cuttlefish" images are clearly the L2 to the L1 "squid".

The incorrect animations seem to be a confusion with the EE's AE_ext_monsters_Young_Cuttle_Fish, which has these images (and looks completely different to the Giant Squid, despite the similar names):
```

    {DEFENSE_ANIM "units/monsters/young-cuttlefish-defend-2.png" "units/monsters/young-cuttlefish-defend-1.png" squishy-hit.wav }
    [death]
        [frame]
            image="units/monsters/young-cuttlefish-die-[1~6].png:100"
        [/frame]
    [/death]
```

**Comment by sevu** [comment]
Would be fixed now, let us know if there are more (except attack icons in ELE, these are known).
Didn't rename images, so Ageless can be updated without Ageless Resources.
