### ISSUE TITLE
Image Paths starting with double slash

### ISSUE THREAD

**Issue by sevu** [ProditorMagnus/Ageless-for-1-14#14]
What's this about with the // for image paths. They seem to come all from the same era, IIRC rashy era.
Well, at least on windows it works.
https://units.wesnoth.org/1.14/Ageless_Era/error.html

**Comment by ProditorMagnus** [comment]
ELE, not RE.

**Comment by ProditorMagnus** [comment]
@ghype

**Comment by ghype** [comment]
bitron mention, back when I created this, the // is useless, but also said they are not harmful. 
guess i forgot to do that. I can do fix it for next release though.
