### ISSUE TITLE
[unit_type][variation] without a variation_id

### ISSUE THREAD

**Issue by stevecotton** [ProditorMagnus/Ageless-for-1-14#30]
With Ageless 4.28.0, Wesnoth 1.16 prints the warning `error config: Skipping duplicate unit variation ID: ''` several times when starting a multiplayer game. Having adding a bit more debugging, the unit_types involved are:

* `AE_efm_dalefolk_Wilderman` 4 times (might be 5, I think the first one without a `variation_id` is accepted)
* `AE_efm_dalefolk_shifter` 5 times (might be 6)
* `AE_mag_Walking_Corpse` 19 or 20 times
* `AE_rhy_tr_Sentinel` 2 or 3 times

**Comment by ProditorMagnus** [comment]
There has been something unreliable about dalefolk variations, I had to remove them from orocia lists.

**Comment by ProditorMagnus** [comment]
> variation_id: The id of this variation. Defaults to variation_name.

Looks like this warning should be ignored.

**Comment by stevecotton** [comment]
I did a test, and corrected that Wiki page you quoted. :(

In debug mode, create a `AE_mag_Walking_Corpse`. There's an edge case with the first variation that has no id: creating a unit with debug mode will default to the variation with `variation_name=wyvern`, which is the first one with no id, instead of creating the base unit.

Hovering over that unit, the debug commands:
* `:unit variation=camel` - selects a variation by id (changes the graphics but not the stats)
* `:unit variation=wyvernrider` - selects a variation by id (again, just the graphics)
* `:unit variation=anything_unknown` - changes to the graphic to `zombie-sister.png`, which is the graphic for the base unit
* `:unit variation=wyvern` - also `zombie-sister.png`, even though this matches a `variation_name` it doesn't match a `variation_id`
* `:unit variation=` - a blank id gets the wyvern image

I've just noticed that this is an EoMa unit, and the missing ids have been added in the EoMa version.

In Wesnoth's codebase, [724dd0f9](https://github.com/wesnoth/wesnoth/commit/724dd0f9491babb4b8733f395c2363f06a20c1bf) is supposed to fall back to the `variant_name`, but this is only in code for displaying the help.

**Comment by sevu** [comment]
> (changes the graphics but not the stats)

I came along that recently too … what I got from it (when using WML instead of debug mode) that using the `[transform_unit]` tag – and transforming to itself instead of some other unit – will change the stats afterwards as well.

https://github.com/Robertdebrus/ANLEra/blob/master/units/dunefolk/Civilian.cfg#L110-L143
