### ISSUE TITLE
orc's shieldbearer small bug

### ISSUE THREAD

**Issue by andrzejskutela** [ProditorMagnus/Ageless-for-1-14#8]
Hello

faction Feudal - Orcish Khaganates
unit Shieldbearer (potentially the whole tree)
issue - you can use the "defend only" weapon on offence

Regards

**Comment by ProditorMagnus** [comment]
Works for me, though [disable] has proven to be unreliable before https://github.com/wesnoth/wesnoth/issues/3324

**Comment by ProditorMagnus** [comment]
Comment if this issue still exists.
